name: Build website

on:
  push:
    branches:
      - main

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build website
        run: python3 site.py

      - name: Copy generated site
        run: |
          mkdir /public
          cp index.html public/

      - name: Build pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: "public/"


  deploy-pages:
    needs: build-pages

    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
        # don't forget to go to the settings/environment and to allow main to push !
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
